export type ContactType = 'tenant' | 'buyer' | 'landlord' | 'seller' | 'prospect' | 'vendor' | 'colleague';
export type PropertyType = 'industrial' | 'office' | 'land' | 'flex' | 'retail';
export type DealStage = 'prospect' | 'qualifying' | 'touring' | 'loi' | 'negotiation' | 'under_contract' | 'closed_won' | 'closed_lost';
export type Priority = 'high' | 'medium' | 'low';
export type ActivityType = 'call' | 'email' | 'meeting' | 'tour' | 'note' | 'loi_sent' | 'loi_received' | 'proposal';
export type ReminderStatus = 'pending' | 'snoozed' | 'completed' | 'dismissed';

export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  company: string;
  title: string;
  email: string;
  phone: string;
  type: ContactType;
  tags: string[];
  notes: string;
  createdAt: string;
  lastContactedAt: string | null;
  nextFollowUp: string | null;
  priority: Priority;
  propertyInterests: string[];
  marketArea: string;
  dealIds: string[];
}

export interface Deal {
  id: string;
  name: string;
  stage: DealStage;
  contactId: string;
  propertyType: PropertyType;
  propertyAddress: string;
  squareFeet: number;
  dealValue: number;
  probability: number;
  notes: string;
  createdAt: string;
  updatedAt: string;
  expectedCloseDate: string;
  tags: string[];
  activities: Activity[];
}

export interface Activity {
  id: string;
  type: ActivityType;
  contactId: string;
  dealId?: string;
  subject: string;
  description: string;
  date: string;
  createdAt: string;
}

export interface Reminder {
  id: string;
  contactId: string;
  dealId?: string;
  title: string;
  description: string;
  dueDate: string;
  status: ReminderStatus;
  priority: Priority;
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface EmailEntry {
  id: string;
  from: string;
  to: string;
  subject: string;
  body: string;
  date: string;
  contactId?: string;
  dealId?: string;
  isInbound: boolean;
  isRead: boolean;
}

export interface AISuggestion {
  id: string;
  type: 'follow_up' | 'deal_risk' | 'opportunity' | 'reminder' | 'outreach';
  title: string;
  description: string;
  contactId?: string;
  dealId?: string;
  priority: Priority;
  actionLabel: string;
  createdAt: string;
  isDismissed: boolean;
}

export interface DailyDigest {
  date: string;
  overdueTasks: Reminder[];
  todayTasks: Reminder[];
  dealsAtRisk: Deal[];
  coldContacts: Contact[];
  suggestions: AISuggestion[];
  stats: {
    activeDeals: number;
    totalPipelineValue: number;
    closedThisMonth: number;
    activitiesThisWeek: number;
  };
}

export const DEAL_STAGES: { key: DealStage; label: string; color: string }[] = [
  { key: 'prospect', label: 'Prospect', color: '#6b7280' },
  { key: 'qualifying', label: 'Qualifying', color: '#8b5cf6' },
  { key: 'touring', label: 'Touring', color: '#3b82f6' },
  { key: 'loi', label: 'LOI', color: '#f59e0b' },
  { key: 'negotiation', label: 'Negotiation', color: '#f97316' },
  { key: 'under_contract', label: 'Under Contract', color: '#10b981' },
  { key: 'closed_won', label: 'Closed Won', color: '#059669' },
  { key: 'closed_lost', label: 'Closed Lost', color: '#ef4444' },
];

export const CONTACT_TYPES: { key: ContactType; label: string }[] = [
  { key: 'tenant', label: 'Tenant' },
  { key: 'buyer', label: 'Buyer' },
  { key: 'landlord', label: 'Landlord' },
  { key: 'seller', label: 'Seller' },
  { key: 'prospect', label: 'Prospect' },
  { key: 'vendor', label: 'Vendor' },
  { key: 'colleague', label: 'Colleague' },
];

export const PROPERTY_TYPES: { key: PropertyType; label: string }[] = [
  { key: 'industrial', label: 'Industrial' },
  { key: 'office', label: 'Office' },
  { key: 'land', label: 'Land' },
  { key: 'flex', label: 'Flex/R&D' },
  { key: 'retail', label: 'Retail' },
];
